Link Updates
m2n037/awesome-mecheng pull request #41
Opened 2018-03-17 17:35 UTC by MechEngKnowledgeMap

2018-03-17 18:00 UTC, pwab requested changes
As far as I can see you tried to include this map into the repository itself instead of linking to it. IMHO this shouldn't be done because this is a link-list.

Also files like `Units 1.pdf` and `convert.exe` (wtf!?) don't belong here.

The link to the NASA FEMCI book seems to be okay. The rest should be removed.

Also you should try to keep your commit history clean.

2018-03-17 23:17 UTC, Clockmaker requested changes
You are still pushing bogus files (pdf, html, txt etc...)

https://github.com/htmlpreview/htmlpreview.github.com doesn't work on my browser.

2018-03-17 23:17 UTC, Clockmaker commented on README.md
> +* [MECHANICAL ENGINEERING DESIGN](http://htmlpreview.github.io/?https://github.com/MechEngKnowledgeMap/awesome-mecheng/blob/gh-branches/docs/index.htm), knowledge maps with selectable links
the existing link seems fine

2018-03-17 23:22 UTC, Clockmaker requested changes

2018-03-17 23:22 UTC, Clockmaker commented on README.md
> +* [In Tech open](http://www.intechopen.com/)
intechopen is already included under *Open Courses*

2018-03-17 23:47 UTC, Clockmaker commented on README.md
> +* [In Tech open](http://www.intechopen.com/)
http://www.roymech.co.uk/ is under development, but the author passed away...
I don't know how to feel about that, but most of the content seems fine.

2018-03-17 23:58 UTC, Clockmaker commented
From what I've seen you are attempting to clone http://www.engineer-assist.com/KnowledgeMap/ here.
I'm pretty sure it's against the GPL license, but I can be wrong.

Maybe you can start a different repo and link that instead.
*By the way* all the link on the graph are dead.

2018-03-18 16:57 UTC, MechEngKnowledgeMap commented
Dear Mukunda

Yes some of the links on the http://www.engineer-assist.com/KnowledgeMap/ are
dead, that is why I want to clone the site and fix the links.

If some of the links on http://www.engineer-assist.com
<http://www.engineer-assist.com/KnowledgeMap/> work I will link rather to
their site? What do you think? That is why I created a gh-branch.

Thank you,

Kind Regards,

Taeke

On Sun, Mar 18, 2018 at 1:58 AM, Giuseppe Vale <notifications@github.com>
wrote:

> From what I've seen you are attempting to clone
> http://www.engineer-assist.com/KnowledgeMap/ here.
> I'm pretty sure it's against the GPL license, but I can be wrong.
>
> Maybe you can start a different repo and link that instead.
> *By the way* all the link on the graph are dead.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/m2n037/awesome-mecheng/pull/41#issuecomment-373961717>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AjhLBv-yrYER7c4wNKjxCS83a3vSY1fzks5tfaMWgaJpZM4Su5Gb>
> .
>

2018-03-18 18:18 UTC, MechEngKnowledgeMap commented
I will see if I can get http://www.engineer-assist.com/KnowledgeMap/  to fix their links.

I will also update the links as you suggest.

2018-03-18 18:18 UTC, closed without merging